### ISSUE TITLE
Initialize Broadcast variables properly when SparkCLR restores from checkpoint

### ISSUE THREAD

**Issue by tawan0109** [Microsoft/Mobius#292]
When checkpoint is enabled and broadcast variables are also referenced in user code, SparkCLR fails to restore from checkpoint, and below exception is thrown. The root cause is that broadcast variables are not properly initialized before being referenced after restart.

<pre>
[2016-02-03 11:06:57,751] [1] [INFO ] [Microsoft.Spark.CSharp.Worker] - rddInfo: rddId 35, stageId 13, partitionId 1
[2016-02-03 11:06:57,905] [1] [ERROR] [Microsoft.Spark.CSharp.Worker] - System.ArgumentException: Attempted to use broadcast id 0 after it was destroyed.
   at Microsoft.Spark.CSharp.Core.Broadcast`1.get_Value() in d:\SparkWorkspace\Microsoft\SparkCLR\csharp\Adapter\Microsoft.Spark.CSharp\Core\Broadcast.cs:line 97
   at Microsoft.Spark.CSharp.DStreamSamples.UpdateStateByKeyHelper.Execute(IEnumerable`1 vs, Int32 s) in d:\SparkWorkspace\Microsoft\SparkCLR\csharp\Samples\Microsoft.Spark.CSharp\DStreamSamples.cs:line 63
   at Microsoft.Spark.CSharp.Streaming.UpdateStateByKeyHelper`3.<Execute>b__0(KeyValuePair`2 x) in d:\SparkWorkspace\Microsoft\SparkCLR\csharp\Adapter\Microsoft.Spark.CSharp\Streaming\PairDStreamFunctions.cs:line 616
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.<CastIterator>d__94`1.MoveNext()
   at System.Linq.Enumerable.<CastIterator>d__94`1.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.<CastIterator>d__94`1.MoveNext()
   at Microsoft.Spark.CSharp.Worker.Main(String[] args) in d:\SparkWorkspace\Microsoft\SparkCLR\csharp\Worker\Microsoft.Spark.CSharp\Worker.cs:line 165
</pre>

**Comment by qintao1976** [comment]
This issue has been solved by commit eb63a7a649bdd88e21016168d3fca4499e4dd439.
Thanks
