### ISSUE TITLE
cant stop in  Running sample DStreamTextFileSamples

### ISSUE THREAD

**Issue by LeiTi** [Microsoft/Mobius#48]
may something wrong here.

**Comment by tawan0109** [comment]
Please run the sample with the latest code, there is [commit](https://github.com/Microsoft/SparkCLR/pull/44) about it.

**Comment by qintao1976** [comment]
It takes 7~8 minutes to run this test. This is the output:

[2015-11-12 19:52:13,024] [1] [INFO ] [Microsoft.Spark.CSharp.Samples.SparkCLRSamples] - ----- Running sample DStreamTextFileSamples -----
Connecting to a callback server at port 36060
-------------------------------------------
Time: 1447386734000
-------------------------------------------
[The, 184]
[quick, 176]
[brown, 176]
[fox, 176]
[jumps, 176]
[over, 176]
[the, 176]
[lazy, 184]
[dog, 184]

-------------------------------------------
Time: 1447386736000
-------------------------------------------
[The, 184]
[quick, 176]
[brown, 176]
[fox, 176]
[jumps, 176]
[over, 176]
[the, 176]
[lazy, 184]
[dog, 184]

-------------------------------------------
Time: 1447386738000
-------------------------------------------
[The, 184]
[quick, 176]
[brown, 176]
[fox, 176]
[jumps, 176]
[over, 176]
[the, 176]
[lazy, 184]
[dog, 184]

-------------------------------------------
Time: 1447386740000
-------------------------------------------
[The, 184]
[quick, 176]
[brown, 176]
[fox, 176]
[jumps, 176]
[over, 176]
[the, 176]
[lazy, 184]
[dog, 184]

-------------------------------------------
Time: 1447386742000
-------------------------------------------
[The, 184]
[quick, 176]
[brown, 176]
[fox, 176]
[jumps, 176]
[over, 176]
[the, 176]
[lazy, 184]
[dog, 184]

Requesting to close a call back server.
[2015-11-12 20:02:06,690] [1] [INFO ] [Microsoft.Spark.CSharp.Samples.SparkCLRSamples] - ----- Finished runnning sample DStreamTextFileSamples -----

**Comment by LeiTi** [comment]
ya. thanks. it pass on my machine now.

**Comment by LeiTi** [comment]
em. i found something strange.
if i only run DStreamTextFileSamples function (use `sparkclr.samples.torun` parameter `) , it will success.
however if i run all the samples use command `sparkclr-submit.cmd --verbose --exe SparkCLRSamples.exe  %SPARKCLR_HOME%\samples spark.local.dir C:\temp\SparkCLRTemp sparkclr.sampledata.loc %SPARKCLR_HOME%\data` it will  fail.

and i note that SparkCLRSamples.exe spend 1738.7MB Memory...

This is the output.

[2015-11-13 14:32:04,235] [1] [INFO ] [Microsoft.Spark.CSharp.Samples.SparkCLRSamples] - ----- Running sample DStreamTextFileSamples -----
Connecting to a callback server at port 62296
-------------------------------------------
Time: 1447396326000
-------------------------------------------
[The, 414]
[quick, 396]
[brown, 396]
[fox, 396]
[jumps, 396]
[over, 396]
[the, 396]
[lazy, 414]
[dog, 414]

-------------------------------------------
Time: 1447396328000
-------------------------------------------
[The, 414]
[quick, 396]
[brown, 396]
[fox, 396]
[jumps, 396]
[over, 396]
[the, 396]
[lazy, 414]
[dog, 414]

-------------------------------------------
Time: 1447396330000
-------------------------------------------
[The, 414]
[quick, 396]
[brown, 396]
[fox, 396]
[jumps, 396]
[over, 396]
[the, 396]
[lazy, 414]
[dog, 414]

-------------------------------------------
Time: 1447396332000
-------------------------------------------
[The, 414]
[quick, 396]
[brown, 396]
[fox, 396]
[jumps, 396]
[over, 396]
[the, 396]
[lazy, 414]
[dog, 414]

-------------------------------------------
Time: 1447396334000
-------------------------------------------
[The, 414]
[quick, 396]
[brown, 396]
[fox, 396]
[jumps, 396]
[over, 396]
[the, 396]
[lazy, 414]
[dog, 414]

Requesting to close a call back server.
[2015-11-13 14:34:12,607] [1] [ERROR] [Microsoft.Spark.CSharp.Interop.Ipc.JvmBridge] - Identifier for type %%% not supported
[2015-11-13 14:34:12,609] [1] [ERROR] [Microsoft.Spark.CSharp.Interop.Ipc.JvmBridge] - 
*******************************************************************************************************************************
   at Microsoft.Spark.CSharp.Interop.Ipc.JvmBridge.CallJavaMethod(Boolean isStatic, Object classNameOrJvmObjectReference, String methodName, Object[] parameters) in c:\Users\SparkCLR-master\SparkCLR-master\csharp\Adapter\Microsoft.Spark.CSharp\Interop\Ipc\JvmBridge.cs:line 106
*******************************************************************************************************************************
[2015-11-13 14:34:12,611] [1] [ERROR] [Microsoft.Spark.CSharp.Samples.SparkCLRSamples] - ----- Error runnning sample DStreamTextFileSamples -----
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NotSupportedException: Identifier for type **[nul control character]** not supported
   at Microsoft.Spark.CSharp.Interop.Ipc.JvmBridge.CallJavaMethod(Boolean isStatic, Object classNameOrJvmObjectReference, String methodName, Object[] parameters) in c:\Users\SparkCLR-master\SparkCLR-master\csharp\Adapter\Microsoft.Spark.CSharp\Interop\Ipc\JvmBridge.cs:line 116
   at Microsoft.Spark.CSharp.Interop.Ipc.JvmBridge.CallStaticJavaMethod(String className, String methodName) in c:\Users\SparkCLR-master\SparkCLR-master\csharp\Adapter\Microsoft.Spark.CSharp\Interop\Ipc\JvmBridge.cs:line 36
   at Microsoft.Spark.CSharp.Proxy.Ipc.StreamingContextIpcProxy.Stop() in c:\Users\SparkCLR-master\SparkCLR-master\csharp\Adapter\Microsoft.Spark.CSharp\Proxy\Ipc\StreamingContextIpcProxy.cs:line 50
   at Microsoft.Spark.CSharp.Streaming.StreamingContext.Stop() in c:\Users\SparkCLR-master\SparkCLR-master\csharp\Adapter\Microsoft.Spark.CSharp\Streaming\StreamingContext.cs:line 62
   at Microsoft.Spark.CSharp.DStreamSamples.DStreamTextFileSamples() in c:\Users\SparkCLR-master\SparkCLR-master\csharp\Samples\Microsoft.Spark.CSharp\DStreamSamples.cs:line 94
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Microsoft.Spark.CSharp.Samples.SparkCLRSamples.RunSamples() in c:\Users\SparkCLR-master\SparkCLR-master\csharp\Samples\Microsoft.Spark.CSharp\Program.cs:line 82
[2015-11-13 14:34:12,611] [1] [INFO ] [Microsoft.Spark.CSharp.Samples.SparkCLRSamples] - ----- Running sample DoubleRDVarianceSample -----

**Comment by tawan0109** [comment]
@LeiTi thanks for reporting it. This is a known issue, we are working on it, will update you once it get fixed.

**Comment by qintao1976** [comment]
Now the DStream example is still experimental. I have just checked in some code. Now by default, DStream example will not be ran. You can set command line option:

sparkclr.samples.category all
to run all the examples.

Or 
sparkclr.samples.category DStream

to run only the DStream example.

We are still working on the DStream example. Thanks

**Comment by xiongrenyi** [comment]
streaming is a M2 feature - https://github.com/Microsoft/SparkCLR/milestones
we're working on shutting down streaming program gracefully without impacting other samples after which we'll bring it back

**Comment by xiongrenyi** [comment]
Hi Tao,

Can you change category 'DStream' to 'Experimental'? Daniel raised a good point this morning that people should feel free to add any samples under a different category outside of functional test suite to test their features without impacting others

**Comment by qintao1976** [comment]
It is easy to do that, only need to change the tag from [Sample("DStream")] to [Sample("Experimental")].

My question is: do we need multiple categories for experimental test cases so we can easily run only one category at one time?

If there is no such need, then we can put all experimental test cases in one "Experimental" category.

**Comment by xiongrenyi** [comment]
I think just Experimental is fine for now

Sent from my Windows Phone
________________________________

**Comment by qintao1976** [comment]
Ok, I have changed the tag to "experimental".

So now you should use 
sparkclr.samples.category all
to run all the examples.

Or 
sparkclr.samples.category experimental
to run only experimental examples.

**Comment by skaarthik** [comment]
Closing due to inactivity in this issue
