### ISSUE TITLE
System.NotSupportedException: Spark master value yarn not recognized

### ISSUE THREAD

**Issue by shakdoesgithub** [Microsoft/Mobius#574]
on my worker node, I'm getting this error: 
`System.NotSupportedException: Spark master value yarn not recognized`

I'm running this on AWS EMR with spark 2.0.

I'm starting the job with this command:

`./sparkclr-submit.sh --master yarn-cluster  --exe apacheSpark.sh.exe /home/ec2-user/app/Debug/`

I see that the job is send to two nodes, and both nodes report the same message:
`Spark master value yarn not recognized`

I'm using 2.11-2.0.000-PREVIEW version of the Spark CLR. It seems like the -cluster part of the yarn-cluster argument gets cut off when it's sent to the worker node

**Comment by skaarthik** [comment]
I have never tried using `yarn-cluster` for master config. Can you try `--master yarn --deploy-mode cluster`? These are the config values I have used in YARN following the documentation at https://spark.apache.org/docs/latest/running-on-yarn.html#launching-spark-on-yarn

**Comment by shakdoesgithub** [comment]
same thing, it seems to be coming from this file:
https://github.com/Microsoft/Mobius/blob/1215ae66c6cb8841ad3d65c1ee6fb035c2fcaef1/csharp/Adapter/Microsoft.Spark.CSharp/Configuration/ConfigurationService.cs#L75

**Comment by skaarthik** [comment]
Do you get similar error if you use `client` deploy mode?

**Comment by shakdoesgithub** [comment]
So I just ran it with the client deploy mode:
`/home/ec2-user/mobius/runtime/scripts/sparkclr-submit.sh --master yarn --deploy-mode cluster --exe apacheSpark.sh.exe /home/hadoop`

And i get the following on the terminal after executing the command:

```

[sparkclr-submit.sh] LAUNCH_CLASSPATH=/home/ec2-user/mobius/runtime/lib/spark-clr_2.11-2.0.000-PREVIEW-1.jar:/usr/lib/spark//jars/*
Zip driver directory /home/hadoop to /tmp/hadoop_1475698068055.zip
[sparkclr-submit.sh] Command to run  --master yarn --deploy-mode cluster --name apacheSpark.sh --files /tmp/hadoop_1475698068055.zip --class org.apache.spark.deploy.csharp.CSharpRunner /home/ec2-user/mobius/runtime/lib/spark-clr_2.11-2.0.000-PREVIEW-1.jar hadoop_1475698068055.zip apacheSpark.sh.exe
16/10/05 20:07:50 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
16/10/05 20:07:51 INFO RMProxy: Connecting to ResourceManager at masterNodeIP/masterNodeIP:8032
16/10/05 20:07:51 INFO Client: Requesting a new application from cluster with 2 NodeManagers
16/10/05 20:07:51 INFO Client: Verifying our application has not requested more than the maximum memory capability of the cluster (11520 MB per container)
16/10/05 20:07:51 INFO Client: Will allocate AM container, with 11520 MB memory including 1047 MB overhead
16/10/05 20:07:51 INFO Client: Setting up container launch context for our AM
16/10/05 20:07:51 INFO Client: Setting up the launch environment for our AM container
16/10/05 20:07:51 INFO Client: Preparing resources for our AM container
16/10/05 20:07:51 WARN Client: Neither spark.yarn.jars nor spark.yarn.archive is set, falling back to uploading libraries under SPARK_HOME.
16/10/05 20:07:53 INFO Client: Uploading resource file:/mnt/tmp/spark-ccd6d705-e90a-4c81-952d-2d26c844cca5/__spark_libs__866911260742536503.zip -> hdfs://masterNodeIP:8020/user/root/.sparkStaging/application_1475254717520_0014/__spark_libs__866911260742536503.zip
16/10/05 20:07:55 INFO Client: Uploading resource file:/home/ec2-user/mobius/runtime/lib/spark-clr_2.11-2.0.000-PREVIEW-1.jar -> hdfs://masterNodeIP:8020/user/root/.sparkStaging/application_1475254717520_0014/spark-clr_2.11-2.0.000-PREVIEW-1.jar
16/10/05 20:07:55 INFO Client: Uploading resource file:/tmp/hadoop_1475698068055.zip -> hdfs://masterNodeIP:8020/user/root/.sparkStaging/application_1475254717520_0014/hadoop_1475698068055.zip
16/10/05 20:07:55 INFO Client: Uploading resource file:/mnt/tmp/spark-ccd6d705-e90a-4c81-952d-2d26c844cca5/__spark_conf__4030300207933206838.zip -> hdfs://masterNodeIP:8020/user/root/.sparkStaging/application_1475254717520_0014/__spark_conf__.zip
16/10/05 20:07:55 INFO SecurityManager: Changing view acls to: root
16/10/05 20:07:55 INFO SecurityManager: Changing modify acls to: root
16/10/05 20:07:55 INFO SecurityManager: Changing view acls groups to:
16/10/05 20:07:55 INFO SecurityManager: Changing modify acls groups to:
16/10/05 20:07:55 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(root); groups with view permissions: Set(); users  with modify permissions: Set(root); groups with modify permissions: Set()
16/10/05 20:07:55 INFO Client: Submitting application application_1475254717520_0014 to ResourceManager
16/10/05 20:07:55 INFO YarnClientImpl: Submitted application application_1475254717520_0014
16/10/05 20:07:56 INFO Client: Application report for application_1475254717520_0014 (state: ACCEPTED)
16/10/05 20:07:56 INFO Client:
	 client token: N/A
	 diagnostics: N/A
	 ApplicationMaster host: N/A
	 ApplicationMaster RPC port: -1
	 queue: default
	 start time: 1475698075576
	 final status: UNDEFINED
	 tracking URL: http://masterNodeIP:20888/proxy/application_1475254717520_0014/
	 user: root
16/10/05 20:07:57 INFO Client: Application report for application_1475254717520_0014 (state: ACCEPTED)
16/10/05 20:07:58 INFO Client: Application report for application_1475254717520_0014 (state: ACCEPTED)
16/10/05 20:07:59 INFO Client: Application report for application_1475254717520_0014 (state: ACCEPTED)
16/10/05 20:08:00 INFO Client: Application report for application_1475254717520_0014 (state: ACCEPTED)
16/10/05 20:08:01 INFO Client: Application report for application_1475254717520_0014 (state: ACCEPTED)
16/10/05 20:08:02 INFO Client: Application report for application_1475254717520_0014 (state: ACCEPTED)
16/10/05 20:08:03 INFO Client: Application report for application_1475254717520_0014 (state: ACCEPTED)
16/10/05 20:08:04 INFO Client: Application report for application_1475254717520_0014 (state: ACCEPTED)
16/10/05 20:08:05 INFO Client: Application report for application_1475254717520_0014 (state: ACCEPTED)
16/10/05 20:08:06 INFO Client: Application report for application_1475254717520_0014 (state: ACCEPTED)
16/10/05 20:08:07 INFO Client: Application report for application_1475254717520_0014 (state: ACCEPTED)
16/10/05 20:08:08 INFO Client: Application report for application_1475254717520_0014 (state: FAILED)
16/10/05 20:08:08 INFO Client:
	 client token: N/A
	 diagnostics: Application application_1475254717520_0014 failed 2 times due to AM Container for appattempt_1475254717520_0014_000002 exited with  exitCode: 1
For more detailed output, check application tracking page:http://masterNodeIP:8088/cluster/app/application_1475254717520_0014Then, click on links to logs of each attempt.
Diagnostics: Exception from container-launch.
Container id: container_1475254717520_0014_02_000001
Exit code: 1
Stack trace: ExitCodeException exitCode=1:
	at org.apache.hadoop.util.Shell.runCommand(Shell.java:545)
	at org.apache.hadoop.util.Shell.run(Shell.java:456)
	at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:722)
	at org.apache.hadoop.yarn.server.nodemanager.DefaultContainerExecutor.launchContainer(DefaultContainerExecutor.java:212)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:302)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:82)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)


Container exited with a non-zero exit code 1
Failing this attempt. Failing the application.
	 ApplicationMaster host: N/A
	 ApplicationMaster RPC port: -1
	 queue: default
	 start time: 1475698075576
	 final status: FAILED
	 tracking URL: http://masterNodeIP:8088/cluster/app/application_1475254717520_0014
	 user: root
Exception in thread "main" org.apache.spark.SparkException: Application application_1475254717520_0014 finished with failed status
	at org.apache.spark.deploy.yarn.Client.run(Client.scala:1132)
	at org.apache.spark.deploy.yarn.Client$.main(Client.scala:1175)
	at org.apache.spark.deploy.yarn.Client.main(Client.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:729)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:185)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:210)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:124)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
16/10/05 20:08:08 INFO ShutdownHookManager: Shutdown hook called
16/10/05 20:08:08 INFO ShutdownHookManager: Deleting directory /mnt/tmp/spark-ccd6d705-e90a-4c81-952d-2d26c844cca5
```

On the worker node I get the following:
```
[CSharpRunner.main] Unzipping driver hadoop_1475698068055.zip in /mnt1/yarn/usercache/root/appcache/application_1475254717520_0014/container_1475254717520_0014_02_000001
[CSharpRunner.main] Starting CSharpBackend!
[CSharpRunner.main] Port number used by CSharpBackend is 46292
[CSharpRunner.main] adding key=spark.sql.warehouse.dir and value=hdfs:///user/spark/warehouse to environment
[CSharpRunner.main] adding key=spark.yarn.dist.files and value=file:/tmp/hadoop_1475698068055.zip to environment
[CSharpRunner.main] adding key=spark.executor.extraJavaOptions and value=-verbose:gc -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=70 -XX:MaxHeapFreeRatio=70 -XX:+CMSClassUnloadingEnabled -XX:OnOutOfMemoryError='kill -9 %p' to environment
[CSharpRunner.main] adding key=spark.history.fs.logDirectory and value=hdfs:///var/log/spark/apps to environment
[CSharpRunner.main] adding key=spark.eventLog.enabled and value=true to environment
[CSharpRunner.main] adding key=spark.ui.port and value=0 to environment
[CSharpRunner.main] adding key=spark.shuffle.service.enabled and value=true to environment
[CSharpRunner.main] adding key=spark.driver.extraLibraryPath and value=/usr/lib/hadoop/lib/native:/usr/lib/hadoop-lzo/lib/native to environment
[CSharpRunner.main] adding key=spark.yarn.historyServer.address and value=masterNodeIP:18080 to environment
[CSharpRunner.main] adding key=spark.yarn.app.id and value=application_1475254717520_0014 to environment
[CSharpRunner.main] adding key=spark.app.name and value=apacheSpark.sh to environment
[CSharpRunner.main] adding key=spark.driver.memory and value=10473M to environment
[CSharpRunner.main] adding key=spark.executor.instances and value=2 to environment
[CSharpRunner.main] adding key=spark.default.parallelism and value=32 to environment
[CSharpRunner.main] adding key=spark.yarn.app.container.log.dir and value=/var/log/hadoop-yarn/containers/application_1475254717520_0014/container_1475254717520_0014_02_000001 to environment
[CSharpRunner.main] adding key=spark.driver.extraJavaOptions and value=-XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=70 -XX:MaxHeapFreeRatio=70 -XX:+CMSClassUnloadingEnabled -XX:OnOutOfMemoryError='kill -9 %p' to environment
[CSharpRunner.main] adding key=spark.submit.deployMode and value=cluster to environment
[CSharpRunner.main] adding key=spark.master and value=yarn to environment
[CSharpRunner.main] adding key=spark.ui.filters and value=org.apache.hadoop.yarn.server.webproxy.amfilter.AmIpFilter to environment
[CSharpRunner.main] adding key=spark.executor.extraLibraryPath and value=/usr/lib/hadoop/lib/native:/usr/lib/hadoop-lzo/lib/native to environment
[CSharpRunner.main] adding key=spark.executor.memory and value=9658M to environment
[CSharpRunner.main] adding key=spark.driver.extraClassPath and value=/usr/lib/hadoop-lzo/lib/*:/usr/lib/hadoop/hadoop-aws.jar:/usr/share/aws/aws-java-sdk/*:/usr/share/aws/emr/emrfs/conf:/usr/share/aws/emr/emrfs/lib/*:/usr/share/aws/emr/emrfs/auxlib/*:/usr/share/aws/emr/security/conf:/usr/share/aws/emr/security/lib/* to environment
[CSharpRunner.main] adding key=spark.eventLog.dir and value=hdfs:///var/log/spark/apps to environment
[CSharpRunner.main] adding key=spark.dynamicAllocation.enabled and value=true to environment
[CSharpRunner.main] adding key=spark.executor.extraClassPath and value=/usr/lib/hadoop-lzo/lib/*:/usr/lib/hadoop/hadoop-aws.jar:/usr/share/aws/aws-java-sdk/*:/usr/share/aws/emr/emrfs/conf:/usr/share/aws/emr/emrfs/lib/*:/usr/share/aws/emr/emrfs/auxlib/*:/usr/share/aws/emr/security/conf:/usr/share/aws/emr/security/lib/* to environment
[CSharpRunner.main] adding key=spark.executor.cores and value=8 to environment
[CSharpRunner.main] adding key=spark.history.ui.port and value=18080 to environment
[CSharpRunner.main] adding key=spark.org.apache.hadoop.yarn.server.webproxy.amfilter.AmIpFilter.param.PROXY_HOSTS and value=masterNodeIP to environment
[CSharpRunner.main] adding key=spark.org.apache.hadoop.yarn.server.webproxy.amfilter.AmIpFilter.param.PROXY_URI_BASES and value=http://masterNodeIP:20888/proxy/application_1475254717520_0014 to environment
[CSharpRunner.main] adding key=spark.hadoop.yarn.timeline-service.enabled and value=false to environment

Unhandled Exception:
System.NotSupportedException: Spark master value yarn not recognized
  at Microsoft.Spark.CSharp.Configuration.ConfigurationService..ctor () [0x000fb] in <1e6c4c1c035440aab88b03ba600f20f6>:0 
  at Microsoft.Spark.CSharp.Interop.SparkCLREnvironment.get_ConfigurationService () [0x00009] in <1e6c4c1c035440aab88b03ba600f20f6>:0 
  at Microsoft.Spark.CSharp.Proxy.Ipc.SparkCLRIpcProxy..ctor () [0x0001b] in <1e6c4c1c035440aab88b03ba600f20f6>:0 
  at Microsoft.Spark.CSharp.Interop.SparkCLREnvironment.get_SparkCLRProxy () [0x00009] in <1e6c4c1c035440aab88b03ba600f20f6>:0 
  at Microsoft.Spark.CSharp.Core.SparkConf..ctor (System.Boolean loadDefaults) [0x0001b] in <1e6c4c1c035440aab88b03ba600f20f6>:0 
  at apacheSpark.WordCountExample.Main (System.String[] args) [0x0001f] in <752d97fc36f141bc935d3f08e7c6fe38>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.NotSupportedException: Spark master value yarn not recognized
  at Microsoft.Spark.CSharp.Configuration.ConfigurationService..ctor () [0x000fb] in <1e6c4c1c035440aab88b03ba600f20f6>:0 
  at Microsoft.Spark.CSharp.Interop.SparkCLREnvironment.get_ConfigurationService () [0x00009] in <1e6c4c1c035440aab88b03ba600f20f6>:0 
  at Microsoft.Spark.CSharp.Proxy.Ipc.SparkCLRIpcProxy..ctor () [0x0001b] in <1e6c4c1c035440aab88b03ba600f20f6>:0 
  at Microsoft.Spark.CSharp.Interop.SparkCLREnvironment.get_SparkCLRProxy () [0x00009] in <1e6c4c1c035440aab88b03ba600f20f6>:0 
  at Microsoft.Spark.CSharp.Core.SparkConf..ctor (System.Boolean loadDefaults) [0x0001b] in <1e6c4c1c035440aab88b03ba600f20f6>:0 
  at apacheSpark.WordCountExample.Main (System.String[] args) [0x0001f] in <752d97fc36f141bc935d3f08e7c6fe38>:0 
[CSharpRunner.main] closing CSharpBackend
Requesting to close all call back sockets.
[CSharpRunner.main] Return CSharpBackend code 1
```

**Comment by skaarthik** [comment]
The command line you shared and the log messages have `cluster` as the deploy mode. Can you try with `client` as the deploy mode and share the output/log messages?

**Comment by skaarthik** [comment]
@shakdoesgithub thanks for reporting this issue. I just noticed that Mobius was not updated to reflect the [change in Spark's arguments for YARN](https://github.com/apache/spark/blob/4bafacaa5f50a3e986c14a38bc8df9bae303f3a0/core/src/main/scala/org/apache/spark/deploy/SparkSubmit.scala#L235) in Spark 2.0.  Fix is on the way. Expect a PR to Mobius on this soon.

**Comment by skaarthik** [comment]
Issue fixed in https://github.com/Microsoft/Mobius/commit/7d920d12065c68759b1856949e096a2ca8e0486c
Fix is available in https://github.com/Microsoft/Mobius/releases/tag/v2.0.000-PREVIEW-2
