### ISSUE TITLE
System.NullReferenceException when executing SparkClrPi.exe in local mode

### ISSUE THREAD

**Issue by EdStone** [Microsoft/Mobius#585]
Hi All:

While running your example, I am getting the error above.
I am able to run PySpark jobs so I am reasonably confident that all is installed on my system.

Attached is the console output of the running job.
[Log.txt](https://github.com/Microsoft/Mobius/files/525260/Log.txt)

Please advise.
Thank you very much, appreciate.

**Comment by skaarthik** [comment]
@EdStone it looks like you do not have %HADOOP_HOME%\bin directory in your machine. Refer to the pre-requisites section in https://github.com/Microsoft/Mobius/blob/master/notes/running-mobius-app.md#pre-requisites. You need to download [winutils.exe](https://github.com/MobiusForSpark/winutils/blob/master/hadoop-2.6.0/bin/winutils.exe?raw=true) to something like `c:\temp\winutils\bin` and set `HADOOP_HOME` environment variable to `c:\temp\winutils` in your command prompt before running Mobius apps.

**Comment by EdStone** [comment]
Hi  skaarthik:

Thank you very much for replying.

I actually do have %HADOOP_HOME% defined, %HADOOP_HOME%\bin in the path and winutils.exe in the correct location (please see console output below).

Could it be something related to Python installation (ex. do I need to install Python, if so, which version ... 2.7 or 3.5, etc.)?

Thank you,
Edward

my console input / output:

C:\devel\spark-clr_2.10-1.6.200\runtime\scripts>echo %HADOOP_HOME%
C:\devel\hadoop

C:\devel\spark-clr_2.10-1.6.200\runtime\scripts>dir %HADOOP_HOME%\bin
 Volume in drive C has no label.
 Volume Serial Number is 9E1F-EE73

 Directory of C:\devel\hadoop\bin

10/12/2016  06:56 PM    <DIR>          .
10/12/2016  06:56 PM    <DIR>          ..
08/17/2016  09:49 PM           108,813 container-executor
08/17/2016  09:49 PM             6,488 hadoop
08/17/2016  09:49 PM             8,514 hadoop.cmd
08/17/2016  09:49 PM            12,223 hdfs
08/17/2016  09:49 PM             7,238 hdfs.cmd
08/17/2016  09:49 PM             5,953 mapred
08/17/2016  09:49 PM             6,094 mapred.cmd
08/17/2016  09:49 PM             1,776 rcc
08/17/2016  09:49 PM           125,269 test-container-executor
10/12/2016  06:55 PM           108,032 winutils.exe
11/03/2013  01:14 PM           371,712 winutils.pdb
08/17/2016  09:49 PM            13,352 yarn
08/17/2016  09:49 PM            11,054 yarn.cmd
              13 File(s)        786,518 bytes
               2 Dir(s)  90,876,231,680 bytes free

C:\devel\spark-clr_2.10-1.6.200\runtime\scripts>where winutils.exe
C:\devel\hadoop\bin\winutils.exe

**Comment by skaarthik** [comment]
You do not need Python installed for Mobius. Where did you get winutils.exe from? There is a possibility that it may not be compatible with the hadoop version your Spark build is compiled against. Try downloading winutils.exe from the path I shared in my previous response. If that does not work, you need to look into Spark log to find out what exactly going on. Set log level to DEBUG in log4j.properties in Spark's conf folder and update `spark-defaults.conf` as described in  http://stackoverflow.com/a/28457062 to point to the updated log4j.properties. That should dump all the information you need to figure out what's going on. Feel free to share the generated log file or copy relevant sections if you are not able to figure out the root cause.

**Comment by EdStone** [comment]
Hi skaarthik:

Thank you for the quick reply.

1. I downloaded winutils.exe from the path that you provided
2. As per your suggestions, I changed Spark to generate the log file.  It is attached.  The error seems to be related to Python.

Thank you,
E

[application.log.txt](https://github.com/Microsoft/Mobius/files/525931/application.log.txt)

**Comment by skaarthik** [comment]
You might be hitting the first error mentioned in [Troubleshooting Mobius](https://github.com/Microsoft/Mobius/blob/master/notes/troubleshooting-mobius.md#troubleshoot-errors-in-mobius-apps). Try adding `--conf spark.local.dir=c:\temp` to the command line when using sparkclr-submit.cmd.

**Comment by EdStone** [comment]
Hi skaarthik:

Done that (please see the first line of the attached cmd.txt).
Does not seem to help.

The attached files are the command line output and spark log file from the latest run.

Thank you,
Edward
[application.log.txt](https://github.com/Microsoft/Mobius/files/526104/application.log.txt)
[cmd.txt](https://github.com/Microsoft/Mobius/files/526103/cmd.txt)

**Comment by skaarthik** [comment]
Ed, I am running out of ideas on what could be causing this issue. For some reason, CSharpWorker.exe that is launched to perform the execution of C# code crashes. I do not know what might be causing that. 

Are you using SparkClrPi.exe that is available in `examples` folder in Mobius release? If not, can you try using that? Here is the command to use:

`C:\devel\spark-clr_2.10-1.6.200\runtime\scripts>sparkclr-submit.cmd --total-executor-cores 2 --conf spark.local.dir=C:\temp --exe SparkClrPi.exe C:\devel\spark-clr_2.10-1.6.200\examples\Batch\pi`

`examples` directory should be in the same directory as `runtime` directory.

**Comment by assafi** [comment]
FWIW, I'm hitting the same issue on a different project. 
I have written a one-to-one replica of your word count example and I get:

16/10/14 19:29:41 ERROR Executor: Exception in task 0.0 in stage 0.0 (TID 0)
java.lang.NullPointerException
        at scala.collection.mutable.ArrayOps$ofRef$.newBuilder$extension(ArrayOps.scala:190)
        at scala.collection.mutable.ArrayOps$ofRef.newBuilder(ArrayOps.scala:186)
        at scala.collection.TraversableLike$class.filterImpl(TraversableLike.scala:246)
...

**Comment by skaarthik** [comment]
@assafi are you able to run SparkPi example included in the Mobius release? Please confirm if you could run it using the command in my previous comment.

**Comment by skaarthik** [comment]
[`TargetFramework`](https://msdn.microsoft.com/en-us/library/bb398202.aspx#Anchor_1) setting in all C# projects in Mobius repo is `.NET Framework 4.5`. I am wondering if the issue you are seeing is due to the difference in .NET framework versions between Mobius release and your project.

**Comment by assafi** [comment]
Changing the target framework did not solve the problem. Here's the full stack trace:

```
16/10/17 18:59:04 ERROR Executor: Exception in task 0.0 in stage 0.0 (TID 0)
java.lang.NullPointerException
        at scala.collection.mutable.ArrayOps$ofRef$.newBuilder$extension(ArrayOps.scala:190)
        at scala.collection.mutable.ArrayOps$ofRef.newBuilder(ArrayOps.scala:186)
        at scala.collection.TraversableLike$class.filterImpl(TraversableLike.scala:246)
        at scala.collection.TraversableLike$class.filter(TraversableLike.scala:259)
        at scala.collection.mutable.ArrayOps$ofRef.filter(ArrayOps.scala:186)
        at org.apache.spark.api.csharp.CSharpRDD.unzip(CSharpRDD.scala:115)
        at org.apache.spark.api.csharp.CSharpRDD.compute(CSharpRDD.scala:46)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:319)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:283)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:70)
        at org.apache.spark.scheduler.Task.run(Task.scala:85)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:274)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
16/10/17 18:59:04 ERROR Executor: Exception in task 2.0 in stage 0.0 (TID 2)
java.lang.NullPointerException
        at scala.collection.mutable.ArrayOps$ofRef$.newBuilder$extension(ArrayOps.scala:190)
        at scala.collection.mutable.ArrayOps$ofRef.newBuilder(ArrayOps.scala:186)
        at scala.collection.TraversableLike$class.filterImpl(TraversableLike.scala:246)
        at scala.collection.TraversableLike$class.filter(TraversableLike.scala:259)
        at scala.collection.mutable.ArrayOps$ofRef.filter(ArrayOps.scala:186)
        at org.apache.spark.api.csharp.CSharpRDD.unzip(CSharpRDD.scala:115)
        at org.apache.spark.api.csharp.CSharpRDD.compute(CSharpRDD.scala:46)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:319)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:283)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:70)
        at org.apache.spark.scheduler.Task.run(Task.scala:85)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:274)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
16/10/17 18:59:04 ERROR Executor: Exception in task 1.0 in stage 0.0 (TID 1)
java.lang.NullPointerException
        at scala.collection.mutable.ArrayOps$ofRef$.newBuilder$extension(ArrayOps.scala:190)
        at scala.collection.mutable.ArrayOps$ofRef.newBuilder(ArrayOps.scala:186)
        at scala.collection.TraversableLike$class.filterImpl(TraversableLike.scala:246)
        at scala.collection.TraversableLike$class.filter(TraversableLike.scala:259)
        at scala.collection.mutable.ArrayOps$ofRef.filter(ArrayOps.scala:186)
        at org.apache.spark.api.csharp.CSharpRDD.unzip(CSharpRDD.scala:115)
        at org.apache.spark.api.csharp.CSharpRDD.compute(CSharpRDD.scala:46)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:319)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:283)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:70)
        at org.apache.spark.scheduler.Task.run(Task.scala:85)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:274)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
16/10/17 18:59:04 WARN TaskSetManager: Lost task 2.0 in stage 0.0 (TID 2, localhost): java.lang.NullPointerException
        at scala.collection.mutable.ArrayOps$ofRef$.newBuilder$extension(ArrayOps.scala:190)
        at scala.collection.mutable.ArrayOps$ofRef.newBuilder(ArrayOps.scala:186)
        at scala.collection.TraversableLike$class.filterImpl(TraversableLike.scala:246)
        at scala.collection.TraversableLike$class.filter(TraversableLike.scala:259)
        at scala.collection.mutable.ArrayOps$ofRef.filter(ArrayOps.scala:186)
        at org.apache.spark.api.csharp.CSharpRDD.unzip(CSharpRDD.scala:115)
        at org.apache.spark.api.csharp.CSharpRDD.compute(CSharpRDD.scala:46)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:319)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:283)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:70)
        at org.apache.spark.scheduler.Task.run(Task.scala:85)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:274)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by skaarthik** [comment]
@assafi can you try the following two suggestions and let me know if you still see this issue?
* run your driver exe using sparkclr-submit.cmd launched from an admin command prompt
* copy your driver exe (& dependencies) to the same directory as the working Mobius example (Batch\pi directory under examples directory in Mobius release) and run launch your driver exe using sparkclr-submit.cmd. My guess is that the enumeration of files in the directory containing your driver exe is failing for some reason

**Comment by skaarthik** [comment]
BTW, thanks @EdStone and @assafi for trying out the suggestions and sharing the logs. Exception stack trace is not the same in your cases. So, the root cause seems to be different.

**Comment by assafi** [comment]
It appears the source of the problem is Visual Studio, although I suspect spark/mobious has something to do with it as well.
Visual Studio 2015 creates a few locked files in the bin folder (3x *.vshost.* and a *.exe.config).
I suspect spark is trying to zip and unzip the content of this folder but fails because of these files. 

The only way to make this run is to shutoff VS and remove these files, or alternatively copy everything else to another folder.

Is there a way Mobious could exclude those files from whatever .zip spark is trying to do?

**Comment by assafi** [comment]
Another mitigation is to turn off the hosting service in VS and remove any app.config file of course.

**Comment by skaarthik** [comment]
Thanks for the update, @assafi Good to know about the root cause of this issue and the work arounds.

**Comment by skaarthik** [comment]
@EdStone any updates from you on this issue?

**Comment by skaarthik** [comment]
Closing due to inactivity
