### ISSUE TITLE
Cannot able to run or debug SparkClrWordCount examples on Window 10

### ISSUE THREAD

**Issue by jigjosh** [Microsoft/Mobius#631]
hi !
not able to  run or debug the example SparkClrWordCount  getting following error

**JVM method execution failed: Constructor failed for class org.apache.spark.api.csharp.CSharpRDD when called with 9 parameters ([Index=1, Type=JvmObjectReference, Value=11], [Index=2, Type=Byte[], Value=System.Byte[]], [Index=3, Type=JvmObjectReference, Value=8], [Index=4, Type=JvmObjectReference, Value=9], [Index=5, Type=Boolean, Value=False], [Index=6, Type=String, Value=D:\Dummy\Mobius-master\Mobius-master\examples\Batch\WordCount\bin\Debug\CSharpWorker.exe], [Index=7, Type=String, Value=1.0], [Index=8, Type=JvmObjectReference, Value=10], [Index=9, Type=null, Value=null], )**

**pl find the log**
[sparkclr-submit.cmd] SPARKCLR_JAR=spark-clr_2.11-2.0.200.jar 
[sparkclr-submit.cmd] LAUNCH_CLASSPATH="D:\Mobius\runtime\lib\spark-clr_2.11-2.0.200.jar;D:\Spark\jars\*"
[sparkclr-submit.cmd] Command to run --name SparkClrWordCount --class org.apache.spark.deploy.csharp.CSharpRunner D:\Mobius\runtime\lib\spark-clr_2.11-2.0.200.jar D:\Dummy\Mobius-master\Mobius-master\examples\Batch\WordCount\bin\Debug D:\Dummy\Mobius-master\Mobius-master\examples\Batch\WordCount\bin\Debug\SparkClrWordCount.exe  file:///d:/Angular.TXT
[2017-03-11 12:17:17,597] [1] [INFO ] [Microsoft.Spark.CSharp.Configuration.ConfigurationService] - ConfigurationService runMode is LOCAL
[2017-03-11 12:17:17,604] [1] [INFO ] [Microsoft.Spark.CSharp.Configuration.ConfigurationService+SparkCLRConfiguration] - CSharpBackend successfully read from environment variable CSHARPBACKEND_PORT
[2017-03-11 12:17:17,606] [1] [INFO ] [Microsoft.Spark.CSharp.Proxy.Ipc.SparkCLRIpcProxy] - CSharpBackend port number to be used in JvMBridge is 58222
[2017-03-11 12:17:17,720] [1] [INFO ] [Microsoft.Spark.CSharp.Core.SparkConf] - Spark app name set to MobiusWordCount
[2017-03-11 12:17:23,848] [1] [INFO ] [Microsoft.Spark.CSharp.Core.SparkContext] - Reading text file file:///d:/Angular.TXT as RDD<string> with 0 partitions
[2017-03-11 12:17:24,890] [1] [INFO ] [Microsoft.Spark.CSharp.Core.RDD`1[[System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]] - Executing Map operation on RDD (preservesPartitioning=False)
[2017-03-11 12:17:24,993] [1] [DEBUG] [Microsoft.Spark.CSharp.Configuration.ConfigurationService+SparkCLRLocalConfiguration] - Using SparkCLR Adapter dll path to construct CSharpWorkerPath : D:\Dummy\Mobius-master\Mobius-master\examples\Batch\WordCount\bin\Debug\CSharpWorker.exe
[2017-03-11 12:17:25,074] [1] [ERROR] [Microsoft.Spark.CSharp.Interop.Ipc.JvmBridge] - JVM method execution failed: Constructor failed for class org.apache.spark.api.csharp.CSharpRDD when called with 9 parameters ([Index=1, Type=JvmObjectReference, Value=11], [Index=2, Type=Byte[], Value=System.Byte[]], [Index=3, Type=JvmObjectReference, Value=8], [Index=4, Type=JvmObjectReference, Value=9], [Index=5, Type=Boolean, Value=False], [Index=6, Type=String, Value=D:\Dummy\Mobius-master\Mobius-master\examples\Batch\WordCount\bin\Debug\CSharpWorker.exe], [Index=7, Type=String, Value=1.0], [Index=8, Type=JvmObjectReference, Value=10], [Index=9, Type=null, Value=null], )
[2017-03-11 12:17:25,074] [1] [ERROR] [Microsoft.Spark.CSharp.Interop.Ipc.JvmBridge] - java.lang.NoSuchMethodError: org.apache.spark.api.python.PythonFunction.<init>([BLjava/util/Map;Ljava/util/List;Ljava/lang/String;Ljava/lang/String;Ljava/util/List;Lorg/apache/spark/Accumulator;)V
	at org.apache.spark.sql.api.csharp.SQLUtils$.createCSharpFunction(SQLUtils.scala:55)
	at org.apache.spark.api.csharp.CSharpRDD.<init>(CSharpRDD.scala:40)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.apache.spark.api.csharp.CSharpBackendHandler.handleMethodCall(CSharpBackendHandler.scala:167)
	at org.apache.spark.api.csharp.CSharpBackendHandler.handleBackendRequest(CSharpBackendHandler.scala:106)
	at org.apache.spark.api.csharp.CSharpBackendHandler.channelRead0(CSharpBackendHandler.scala:32)
	at org.apache.spark.api.csharp.CSharpBackendHandler.channelRead0(CSharpBackendHandler.scala:28)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:652)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:575)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:489)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:451)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)

[2017-03-11 12:17:25,075] [1] [ERROR] [Microsoft.Spark.CSharp.Interop.Ipc.JvmBridge] - JVM method execution failed: Constructor failed for class org.apache.spark.api.csharp.CSharpRDD when called with 9 parameters ([Index=1, Type=JvmObjectReference, Value=11], [Index=2, Type=Byte[], Value=System.Byte[]], [Index=3, Type=JvmObjectReference, Value=8], [Index=4, Type=JvmObjectReference, Value=9], [Index=5, Type=Boolean, Value=False], [Index=6, Type=String, Value=D:\Dummy\Mobius-master\Mobius-master\examples\Batch\WordCount\bin\Debug\CSharpWorker.exe], [Index=7, Type=String, Value=1.0], [Index=8, Type=JvmObjectReference, Value=10], [Index=9, Type=null, Value=null], )
[2017-03-11 12:17:25,075] [1] [ERROR] [Microsoft.Spark.CSharp.Interop.Ipc.JvmBridge] - 
*******************************************************************************************************************************
   at Microsoft.Spark.CSharp.Interop.Ipc.JvmBridge.CallJavaMethod(Boolean isStatic, Object classNameOrJvmObjectReference, String methodName, Object[] parameters)
*******************************************************************************************************************************
[2017-03-11 12:17:25,075] [1] [ERROR] [Microsoft.Spark.CSharp.Examples.WordCountExample] - Error performing Word Count
[2017-03-11 12:17:25,075] [1] [ERROR] [Microsoft.Spark.CSharp.Examples.WordCountExample] - JVM method execution failed: Constructor failed for class org.apache.spark.api.csharp.CSharpRDD when called with 9 parameters ([Index=1, Type=JvmObjectReference, Value=11], [Index=2, Type=Byte[], Value=System.Byte[]], [Index=3, Type=JvmObjectReference, Value=8], [Index=4, Type=JvmObjectReference, Value=9], [Index=5, Type=Boolean, Value=False], [Index=6, Type=String, Value=D:\Dummy\Mobius-master\Mobius-master\examples\Batch\WordCount\bin\Debug\CSharpWorker.exe], [Index=7, Type=String, Value=1.0], [Index=8, Type=JvmObjectReference, Value=10], [Index=9, Type=null, Value=null], )
[2017-03-11 12:17:25,076] [1] [ERROR] [Microsoft.Spark.CSharp.Examples.WordCountExample] - 
*******************************************************************************************************************************
   at Microsoft.Spark.CSharp.Interop.Ipc.JvmBridge.CallJavaMethod(Boolean isStatic, Object classNameOrJvmObjectReference, String methodName, Object[] parameters)
   at Microsoft.Spark.CSharp.Interop.Ipc.JvmBridge.CallConstructor(String className, Object[] parameters)
   at Microsoft.Spark.CSharp.Proxy.Ipc.SparkContextIpcProxy.CreateCSharpRdd(IRDDProxy prevJvmRddReference, Byte[] command, Dictionary`2 environmentVariables, List`1 pythonIncludes, Boolean preservesPartitioning, List`1 broadcastVariables, List`1 accumulator)
   at Microsoft.Spark.CSharp.Core.PipelinedRDD`1.get_RddProxy()
   at Microsoft.Spark.CSharp.Core.PairRDDFunctions.PartitionBy[K,V](RDD`1 self, Int32 numPartitions, Func`2 partitionFunc)
   at Microsoft.Spark.CSharp.Core.PairRDDFunctions.ReduceByKey[K,V](RDD`1 self, Func`3 reduceFunc, Int32 numPartitions)
   at Microsoft.Spark.CSharp.Examples.WordCountExample.Main(String[] args) in d:\Dummy\Mobius-master\Mobius-master\examples\Batch\WordCount\Program.cs:line 35
*******************************************************************************************************************************
[2017-03-11 12:17:25,078] [1] [INFO ] [Microsoft.Spark.CSharp.Core.SparkContext] - Stopping SparkContext
[2017-03-11 12:17:25,078] [1] [INFO ] [Microsoft.Spark.CSharp.Core.SparkContext] - Note that there might be error in Spark logs on the failure to delete userFiles directory under Spark temp directory (spark.local.dir config value in local mode)
[2017-03-11 12:17:25,078] [1] [INFO ] [Microsoft.Spark.CSharp.Core.SparkContext] - This error may be ignored for now. See https://issues.apache.org/jira/browse/SPARK-8333 for details

**Comment by skaarthik** [comment]
You are probably using an incompatible version of Spark. Make sure you are not using Spark 2.1.0.
Based on the logs above, I can say that Mobius version used is 2.0.200. For this version of Mobius, Spark version should be 2.0.*.

**Comment by jigjosh** [comment]
yes that is the issue

thanks for help !!!!.
