### ISSUE TITLE
not able to run or debug SparkCLRKafka Application on Windows 10 with kafka on docker

### ISSUE THREAD

**Issue by jigjosh** [Microsoft/Mobius#633]
**not able to run or debug SparkCLRKafka Application** 

getting following error 

[sparkclr-submit.cmd] SPARKCLR_JAR=spark-clr_2.11-2.0.200.jar 
[sparkclr-submit.cmd] LAUNCH_CLASSPATH="D:\Mobius\runtime\lib\spark-clr_2.11-2.0.200.jar;D:\Spark\jars\*"
[sparkclr-submit.cmd] Command to run --name SparkClrKafka --class org.apache.spark.deploy.csharp.CSharpRunner D:\Mobius\runtime\lib\spark-clr_2.11-2.0.200.jar D:\Dummy\Mobius-master\Mobius-master\examples\Streaming\Kafka\bin\Debug D:\Dummy\Mobius-master\Mobius-master\examples\Streaming\Kafka\bin\Debug\SparkClrKafka.exe
[2017-03-14 15:30:36,229] [1] [INFO ] [Microsoft.Spark.CSharp.Configuration.ConfigurationService] - ConfigurationService runMode is LOCAL
[2017-03-14 15:30:36,235] [1] [INFO ] [Microsoft.Spark.CSharp.Configuration.ConfigurationService+SparkCLRConfiguration] - CSharpBackend successfully read from environment variable CSHARPBACKEND_PORT
[2017-03-14 15:30:36,237] [1] [INFO ] [Microsoft.Spark.CSharp.Proxy.Ipc.SparkCLRIpcProxy] - CSharpBackend port number to be used in JvMBridge is 61693
[2017-03-14 15:30:36,328] [1] [INFO ] [Microsoft.Spark.CSharp.Core.SparkConf] - Spark app name set to SparkCLRKafka Example
[2017-03-14 15:30:42,917] [1] [INFO ] [Microsoft.Spark.CSharp.Proxy.Ipc.StreamingContextIpcProxy] - Callback server port number is 61734
[2017-03-14 15:30:42,972] [1] [ERROR] [Microsoft.Spark.CSharp.Interop.Ipc.JvmBridge] - **JVM method execution failed: Constructor failed for class org.apache.spark.streaming.kafka.KafkaUtilsPythonHelper when called with no parameters**
[2017-03-14 15:30:42,972] [1] [ERROR] [Microsoft.Spark.CSharp.Interop.Ipc.JvmBridge] - 
[2017-03-14 15:30:42,973] [1] [ERROR] [Microsoft.Spark.CSharp.Interop.Ipc.JvmBridge] - JVM method execution failed: Constructor failed for class org.apache.spark.streaming.kafka.KafkaUtilsPythonHelper when called with no parameters
[2017-03-14 15:30:42,975] [1] [ERROR] [Microsoft.Spark.CSharp.Interop.Ipc.JvmBridge] - 
*******************************************************************************************************************************
   at Microsoft.Spark.CSharp.Interop.Ipc.JvmBridge.CallJavaMethod(Boolean isStatic, Object classNameOrJvmObjectReference, String methodName, Object[] parameters)
*******************************************************************************************************************************

Unhandled Exception: System.Exception: JVM method execution failed: Constructor failed for class org.apache.spark.streaming.kafka.KafkaUtilsPythonHelper when called with no parameters
   at Microsoft.Spark.CSharp.Interop.Ipc.JvmBridge.CallJavaMethod(Boolean isStatic, Object classNameOrJvmObjectReference, String methodName, Object[] parameters)
   at Microsoft.Spark.CSharp.Interop.Ipc.JvmBridge.CallConstructor(String className, Object[] parameters)
   at Microsoft.Spark.CSharp.Proxy.Ipc.StreamingContextIpcProxy.DirectKafkaStream(List`1 topics, IEnumerable`1 kafkaParams, IEnumerable`1 fromOffsets)
   at Microsoft.Spark.CSharp.Streaming.KafkaUtils.CreateDirectStream(StreamingContext ssc, List`1 topics, IEnumerable`1 kafkaParams, IEnumerable`1 fromOffsets)
   at Microsoft.Spark.CSharp.Examples.SparkClrKafkaExample.<>c__DisplayClassd.<Main>b__2() in d:\Dummy\Mobius-master\Mobius-master\examples\Streaming\Kafka\Program.cs:line 62
   at Microsoft.Spark.CSharp.Streaming.StreamingContext.GetOrCreate(String checkpointPath, Func`1 creatingFunc)
   at Microsoft.Spark.CSharp.Examples.SparkClrKafkaExample.Main(String[] args) in d:\Dummy\Mobius-master\Mobius-master\examples\Streaming\Kafka\Program.cs:line 55

**Comment by dwnichols** [comment]
@jigjosh : can you please provide the command line you used to invoke `sparkclr-submit.cmd` ? Thanks

**Comment by skaarthik** [comment]
@jigjosh version mismatch is a possibility here. Share Kafka and Kafka client jar version you are using.

**Comment by jigjosh** [comment]
yes Kafka client jar version is missmatch 
sparkclr-submit.cmd --jars D:\Mobius\runtime\dependencies\spark-streaming-kafka-0-8-assembly_2.11-2.0.0.jar --exe SparkClrKafka.exe D:\Dummy\Mobius-master\Mobius-master\examples\Streaming\Kafka\bin\Debug

will start working 
thanks..
