### ISSUE TITLE
ClassNotFoundException when running EventHub Streaming Example 

### ISSUE THREAD

**Issue by perthcha** [Microsoft/Mobius#635]
### Issue: 
I am getting java.lang.ClassNotFoundException: org.apache.spark.streaming.eventhubs.EventHubsUtils when running the EventHub streaming example.

### Details:
I built the SparkCLREventHubsExample with minimal changes (just the parameter changes in eventHubsParams):

```            
            var sparkContext = new SparkContext(new SparkConf().SetAppName("SparkCLREventHub Example"));
            var eventhubsParams = new Dictionary<string, string>()
            {
                {"eventhubs.policyname", "myreceivepolicy"},
                {"eventhubs.policykey", "Sdyx+lV/qaEPfzKOhYD8EUHIIpD70hIUCV+Jv+3Apy0="},
                {"eventhubs.namespace", "sparkscratch"},
                {"eventhubs.name", "sparkscratch1"},
                {"eventhubs.partition.count", "2"},
                {"eventhubs.consumergroup", "$Default"},
                {"eventhubs.checkpoint.dir", "/EventCheckPoint"},
                {"eventhubs.checkpoint.interval", "10"},
            };
            const int windowDurationInSecs = 5;
            const int slideDurationInSecs = 5;
            const string checkpointPath = "/EventCheckPointSpark";
            const string outputPath = "/EventResult";
```

I ran the exe in HDInsights Spark cluster via the following command:

```
/home/sshuser/mobius/runtime/scripts/sparkclr-submit.sh  --master yarn --deploy-mode client --exe SparkClrEventHub.exe /home/sshuser/Release
```

When the code executes, it fails when it gets to the line `var stream = EventHubsUtils.CreateUnionStream(ssc, eventhubsParams);`

```
17/03/14 19:58:24 ERROR CSharpBackendHandler: methods:
17/03/14 19:58:24 ERROR CSharpBackendHandler: public static org.apache.spark.streaming.api.java.JavaDStream org.apache.spark.streaming.api.csharp.EventHubsUtils.createUnionStream(org.apache.spark.streaming.api.java.JavaStreamingContext,scala.collection.immutable.Map,org.apache.spark.storage.StorageLevel)
17/03/14 19:58:24 ERROR CSharpBackendHandler: args:
17/03/14 19:58:24 ERROR CSharpBackendHandler: argType: org.apache.spark.streaming.api.java.JavaStreamingContext, argValue: org.apache.spark.streaming.api.java.JavaStreamingContext@52cbdf90
17/03/14 19:58:24 ERROR CSharpBackendHandler: argType: scala.collection.immutable.HashMap.HashTrieMap, argValue: Map(eventhubs.name -> sparkscratch1, eventhubs.checkpoint.dir -> /EventCheckPoint, eventhubs.consumergroup -> $Default, eventhubs.partition.count -> 2, eventhubs.checkpoint.interval -> 10, eventhubs.policykey -> Sdyx+lV/qaEPfzKOhYD8EUHIIpD70hIUCV+Jv+3Apy0=, eventhubs.namespace -> sparkscratch, eventhubs.policyname -> myreceivepolicy)
17/03/14 19:58:24 ERROR CSharpBackendHandler: argType: org.apache.spark.storage.StorageLevel, argValue: StorageLevel(memory, deserialized, 1 replicas)
[2017-03-14 19:58:24,862] [1] [ERROR] [Microsoft.Spark.CSharp.Interop.Ipc.JvmBridge] - JVM method execution failed: Static method createUnionStream failed for class org.apache.spark.streaming.api.csharp.EventHubsUtils when called with 3 parameters ([Index=1, Type=JvmObjectReference, Value=10], [Index=2, Type=JvmObjectReference, Value=15], [Index=3, Type=JvmObjectReference, Value=16], )
[2017-03-14 19:58:24,862] [1] [ERROR] [Microsoft.Spark.CSharp.Interop.Ipc.JvmBridge] - java.lang.ClassNotFoundException: org.apache.spark.streaming.eventhubs.EventHubsUtils
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at org.apache.spark.util.Utils$.classForName(Utils.scala:228)
        at org.apache.spark.streaming.api.csharp.EventHubsUtils$.createUnionStream(EventHubsUtils.scala:23)
        at org.apache.spark.streaming.api.csharp.EventHubsUtils.createUnionStream(EventHubsUtils.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.api.csharp.CSharpBackendHandler.handleMethodCall(CSharpBackendHandler.scala:156)
        at org.apache.spark.api.csharp.CSharpBackendHandler.handleBackendRequest(CSharpBackendHandler.scala:106)
        at org.apache.spark.api.csharp.CSharpBackendHandler.channelRead0(CSharpBackendHandler.scala:32)
        at org.apache.spark.api.csharp.CSharpBackendHandler.channelRead0(CSharpBackendHandler.scala:28)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
        at java.lang.Thread.run(Thread.java:745)

[2017-03-14 19:58:24,862] [1] [ERROR] [Microsoft.Spark.CSharp.Interop.Ipc.JvmBridge] - JVM method execution failed: Static method createUnionStream failed for class org.apache.spark.streaming.api.csharp.EventHubsUtils when called with 3 parameters ([Index=1, Type=JvmObjectReference, Value=10], [Index=2, Type=JvmObjectReference, Value=15], [Index=3, Type=JvmObjectReference, Value=16], )
[2017-03-14 19:58:24,863] [1] [ERROR] [Microsoft.Spark.CSharp.Interop.Ipc.JvmBridge] -
*******************************************************************************************************************************
  at Microsoft.Spark.CSharp.Interop.Ipc.JvmBridge.CallJavaMethod (Boolean isStatic, System.Object classNameOrJvmObjectReference, System.String methodName, System.Object[] parameters) <0x4094e230 + 0x00153> in <filename unknown>:0
*******************************************************************************************************************************

Unhandled Exception:
System.Exception: JVM method execution failed: Static method createUnionStream failed for class org.apache.spark.streaming.api.csharp.EventHubsUtils when called with 3 parameters ([Index=1, Type=JvmObjectReference, Value=10], [Index=2, Type=JvmObjectReference, Value=15], [Index=3, Type=JvmObjectReference, Value=16], )
  at Microsoft.Spark.CSharp.Interop.Ipc.JvmBridge.CallJavaMethod (Boolean isStatic, System.Object classNameOrJvmObjectReference, System.String methodName, System.Object[] parameters) <0x4094e230 + 0x00153> in <filename unknown>:0
[ERROR] FATAL UNHANDLED EXCEPTION: System.Exception: JVM method execution failed: Static method createUnionStream failed for class org.apache.spark.streaming.api.csharp.EventHubsUtils when called with 3 parameters ([Index=1, Type=JvmObjectReference, Value=10], [Index=2, Type=JvmObjectReference, Value=15], [Index=3, Type=JvmObjectReference, Value=16], )
  at Microsoft.Spark.CSharp.Interop.Ipc.JvmBridge.CallJavaMethod (Boolean isStatic, System.Object classNameOrJvmObjectReference, System.String methodName, System.Object[] parameters) <0x4094e230 + 0x00153> in <filename unknown>:0
```

**Comment by perthcha** [comment]
I just saw that I might need to download jar files before being able to execute this https://github.com/Microsoft/Mobius/blob/master/notes/running-mobius-app.md#wordcount-example-batch

I'll try that now.
