### ISSUE TITLE
Not able to run example of HiveDataFrame

### ISSUE THREAD

**Issue by jayprajapati857** [Microsoft/Mobius#645]
while debugging from visual studio I am getting this error at
 var data = sqlContext.Read().Json("file:///C:/Mobius/build/runtime/data/order.json");

System.Exception was unhandled
  HResult=-2146233088
  Message=JVM method execution failed: Nonstatic method load failed for class 10 when called with no parameters
  Source=Microsoft.Spark.CSharp.Adapter
  StackTrace:
       at Microsoft.Spark.CSharp.Interop.Ipc.JvmBridge.CallJavaMethod(Boolean isStatic, Object classNameOrJvmObjectReference, String methodName, Object[] parameters)
       at Microsoft.Spark.CSharp.Interop.Ipc.JvmBridge.CallNonStaticJavaMethod(JvmObjectReference objectId, String methodName)
       at Microsoft.Spark.CSharp.Proxy.Ipc.DataFrameReaderIpcProxy.Load()
       at Microsoft.Spark.CSharp.Sql.DataFrameReader.Load()
       at Microsoft.Spark.CSharp.Sql.DataFrameReader.Load(String path)
       at Microsoft.Spark.CSharp.Sql.DataFrameReader.Json(String path)
       at DemoSparkHiveDataFrame.Program.Main(String[] args) in e:\Work\Feb\VS 2012\DemoSparkHiveDataFrame\DemoSparkHiveDataFrame\Program.cs:line 29
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException:

**Comment by skaarthik** [comment]
Can you share Scala exception reported in JVM?

**Comment by jayprajapati857** [comment]
@skaarthik : here is the error i got while running the example from cmd,

 [2017-03-26 17:38:54,516] [1] [INFO ] [Microsoft.Spark.CSharp.Configuration.ConfigurationService] - ConfigurationService runMode is LOCAL
[2017-03-26 17:38:54,535] [1] [INFO ] [Microsoft.Spark.CSharp.Configuration.ConfigurationService+SparkCLRConfiguration] - CSharpBackend successfully read from environment variable CSHARPBACKEND_PORT
[2017-03-26 17:38:54,539] [1] [INFO ] [Microsoft.Spark.CSharp.Proxy.Ipc.SparkCLRIpcProxy] - CSharpBackend port number to be used in JvMBridge is 52102
[2017-03-26 17:38:55,164] [3] [DEBUG] [Microsoft.Spark.CSharp.Interop.Ipc.WeakObjectManagerImpl] - Checking objects thread start ...
[2017-03-26 17:38:55,168] [3] [DEBUG] [Microsoft.Spark.CSharp.Interop.Ipc.WeakObjectManagerImpl] - check begin : weakReferences.Count = 1, checkCount: 10
[2017-03-26 17:38:55,179] [3] [DEBUG] [Microsoft.Spark.CSharp.Interop.Ipc.WeakObjectManagerImpl] - check end : released 0 garbage, remain 1 alive, used 12.2012 ms : release garbage used 3.0028 ms, store alive used 9.1984 ms
[2017-03-26 17:38:55,194] [1] [INFO ] [Microsoft.Spark.CSharp.Core.SparkConf] - Spark configuration key-value set to spark.sql.catalogImplementation=hive
[2017-03-26 17:38:58,180] [3] [DEBUG] [Microsoft.Spark.CSharp.Interop.Ipc.WeakObjectManagerImpl] - check begin : weakReferences.Count = 2, checkCount: 10
[2017-03-26 17:38:58,180] [3] [DEBUG] [Microsoft.Spark.CSharp.Interop.Ipc.WeakObjectManagerImpl] - check end : released 0 garbage, remain 2 alive, used 0 ms : release garbage used 0 ms, store alive used 0 ms
[2017-03-26 17:39:00,967] [1] [INFO ] [Microsoft.Spark.CSharp.Sql.SparkSession] - Using DataFrameReader to read input data from external data source
[2017-03-26 17:39:01,181] [3] [DEBUG] [Microsoft.Spark.CSharp.Interop.Ipc.WeakObjectManagerImpl] - check begin : weakReferences.Count = 6, checkCount: 10
[2017-03-26 17:39:01,181] [3] [DEBUG] [Microsoft.Spark.CSharp.Interop.Ipc.WeakObjectManagerImpl] - check end : released 0 garbage, remain 6 alive, used 0 ms : release garbage used 0 ms, store alive used 0 ms
[2017-03-26 17:39:01,462] [1] [INFO ] [Microsoft.Spark.CSharp.Sql.DataFrameReader] - Constructing DataFrame using JSON source C:/Mobius/examples/Sql/HiveDataFrame/bin/Debug/data/people.json
[2017-03-26 17:39:01,463] [1] [INFO ] [Microsoft.Spark.CSharp.Sql.DataFrameReader] - Input data source format for the reader is 'json'
[2017-03-26 17:39:01,486] [1] [INFO ] [Microsoft.Spark.CSharp.Sql.DataFrameReader] - Input key-vaue option for the data source is path=C:/Mobius/examples/Sql/HiveDataFrame/bin/Debug/data/people.json
[2017-03-26 17:39:01,487] [1] [INFO ] [Microsoft.Spark.CSharp.Sql.DataFrameReader] - Loading DataFrame using the reader
[2017-03-26 17:39:04,181] [3] [DEBUG] [Microsoft.Spark.CSharp.Interop.Ipc.WeakObjectManagerImpl] - check begin : weakReferences.Count = 7, checkCount: 10
[2017-03-26 17:39:04,181] [3] [DEBUG] [Microsoft.Spark.CSharp.Interop.Ipc.WeakObjectManagerImpl] - check end : released 0 garbage, remain 7 alive, used 0 ms : release garbage used 0 ms, store alive used 0 ms
[2017-03-26 17:39:07,182] [3] [DEBUG] [Microsoft.Spark.CSharp.Interop.Ipc.WeakObjectManagerImpl] - check begin : weakReferences.Count = 7, checkCount: 10
[2017-03-26 17:39:07,182] [3] [DEBUG] [Microsoft.Spark.CSharp.Interop.Ipc.WeakObjectManagerImpl] - check end : released 0 garbage, remain 7 alive, used 0 ms : release garbage used 0 ms, store alive used 0 ms
[2017-03-26 17:39:08,161] [1] [ERROR] [Microsoft.Spark.CSharp.Interop.Ipc.JvmBridge] - JVM method execution failed: Nonstatic method load failed for class 7 when called with no parameters
[2017-03-26 17:39:08,161] [1] [ERROR] [Microsoft.Spark.CSharp.Interop.Ipc.JvmBridge] - org.apache.spark.SparkException: Job aborted due to stage failure: Task 1 in stage 0.0 failed 1 times, most recent failure: Lost task 1.0 in stage 0.0 (TID 1, localhost): java.lang.NullPointerException
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1010)
        at org.apache.hadoop.util.Shell.runCommand(Shell.java:482)
        at org.apache.hadoop.util.Shell.run(Shell.java:455)
        at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:715)
        at org.apache.hadoop.fs.FileUtil.chmod(FileUtil.java:873)
        at org.apache.hadoop.fs.FileUtil.chmod(FileUtil.java:853)
        at org.apache.spark.util.Utils$.fetchFile(Utils.scala:471)
        at org.apache.spark.executor.Executor$$anonfun$org$apache$spark$executor$Executor$$updateDependencies$5.apply(Executor.scala:488)
        at org.apache.spark.executor.Executor$$anonfun$org$apache$spark$executor$Executor$$updateDependencies$5.apply(Executor.scala:480)
        at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:733)
        at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:99)
        at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:99)
        at scala.collection.mutable.HashTable$class.foreachEntry(HashTable.scala:230)
        at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:40)
        at scala.collection.mutable.HashMap.foreach(HashMap.scala:99)
        at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:732)
        at org.apache.spark.executor.Executor.org$apache$spark$executor$Executor$$updateDependencies(Executor.scala:480)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:252)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

Driver stacktrace:
        at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1450)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1438)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1437)
        at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
        at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1437)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:811)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:811)
        at scala.Option.foreach(Option.scala:257)
        at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:811)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1659)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1618)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1607)
        at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
        at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:632)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:1871)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:1934)
        at org.apache.spark.rdd.RDD$$anonfun$fold$1.apply(RDD.scala:1046)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
        at org.apache.spark.rdd.RDD.withScope(RDD.scala:358)
        at org.apache.spark.rdd.RDD.fold(RDD.scala:1040)
        at org.apache.spark.sql.execution.datasources.json.InferSchema$.infer(InferSchema.scala:68)
        at org.apache.spark.sql.execution.datasources.json.JsonFileFormat.inferSchema(JsonFileFormat.scala:61)
        at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$15.apply(DataSource.scala:392)
        at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$15.apply(DataSource.scala:392)
        at scala.Option.orElse(Option.scala:289)
        at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:391)
        at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:149)
        at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:122)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.spark.api.csharp.CSharpBackendHandler.handleMethodCall(CSharpBackendHandler.scala:156)
        at org.apache.spark.api.csharp.CSharpBackendHandler.handleBackendRequest(CSharpBackendHandler.scala:106)
        at org.apache.spark.api.csharp.CSharpBackendHandler.channelRead0(CSharpBackendHandler.scala:32)
        at org.apache.spark.api.csharp.CSharpBackendHandler.channelRead0(CSharpBackendHandler.scala:28)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1010)
        at org.apache.hadoop.util.Shell.runCommand(Shell.java:482)
        at org.apache.hadoop.util.Shell.run(Shell.java:455)
        at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:715)
        at org.apache.hadoop.fs.FileUtil.chmod(FileUtil.java:873)
        at org.apache.hadoop.fs.FileUtil.chmod(FileUtil.java:853)
        at org.apache.spark.util.Utils$.fetchFile(Utils.scala:471)
        at org.apache.spark.executor.Executor$$anonfun$org$apache$spark$executor$Executor$$updateDependencies$5.apply(Executor.scala:488)
        at org.apache.spark.executor.Executor$$anonfun$org$apache$spark$executor$Executor$$updateDependencies$5.apply(Executor.scala:480)
        at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:733)
        at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:99)
        at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:99)
        at scala.collection.mutable.HashTable$class.foreachEntry(HashTable.scala:230)
        at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:40)
        at scala.collection.mutable.HashMap.foreach(HashMap.scala:99)
        at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:732)
        at org.apache.spark.executor.Executor.org$apache$spark$executor$Executor$$updateDependencies(Executor.scala:480)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:252)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        ... 1 more

[2017-03-26 17:39:08,176] [1] [ERROR] [Microsoft.Spark.CSharp.Interop.Ipc.JvmBridge] - JVM method execution failed: Nonstatic method load failed for class 7 when called with no parameters
[2017-03-26 17:39:08,300] [1] [ERROR] [Microsoft.Spark.CSharp.Interop.Ipc.JvmBridge] -
*******************************************************************************************************************************
   at Microsoft.Spark.CSharp.Interop.Ipc.JvmBridge.CallJavaMethod(Boolean isStatic, Object classNameOrJvmObjectReference, String methodName, Object[] parameters)
*******************************************************************************************************************************

Unhandled Exception: System.Exception: JVM method execution failed: Nonstatic method load failed for class 7 when called with no parameters
   at Microsoft.Spark.CSharp.Interop.Ipc.JvmBridge.CallJavaMethod(Boolean isStatic, Object classNameOrJvmObjectReference, String methodName, Object[] parameters)
   at Microsoft.Spark.CSharp.Interop.Ipc.JvmBridge.CallNonStaticJavaMethod(JvmObjectReference objectId, String methodName)
   at Microsoft.Spark.CSharp.Proxy.Ipc.DataFrameReaderIpcProxy.Load()
   at Microsoft.Spark.CSharp.Sql.DataFrameReader.Load()
   at Microsoft.Spark.CSharp.Sql.DataFrameReader.Load(String path)
   at Microsoft.Spark.CSharp.Sql.DataFrameReader.Json(String path)
   at Microsoft.Spark.CSharp.Examples.HiveDataFrameExample.Main(String[] args) in C:\Mobius\examples\Sql\HiveDataFrame\Program.cs:line 32

**Comment by jayprajapati857** [comment]
@skaarthik : here is the command i am executing to run this example: 
sparkclr-submit --exe HiveDataFrame.exe C:\Mobius\examples\Sql\HiveDataFrame\bin\Debug C:/Mobius/examples/Sql/HiveDataFrame/bin/Debug/data/people.json

and also tried this command : 
sparkclr-submit --exe HiveDataFrame.exe C:\Mobius\examples\Sql\HiveDataFrame\bin\Debug  file:///C:/Mobius/examples/Sql/HiveDataFrame/bin/Debug/data/people.json

**Comment by skaarthik** [comment]
'file:///...' Is the format I would recommend using.

Do you have [winutils.exe](https://github.com/Microsoft/Mobius/blob/master/notes/running-mobius-app.md#pre-requisites) in %HADOOP_HOME%\bin folder?

**Comment by jayprajapati857** [comment]
yes i have

**Comment by jayprajapati857** [comment]
@skaarthik : thanks for your reply i got solution i need to set builder.config() to spark.sql.wareouse.dir and works fine.

**Comment by jayprajapati857** [comment]
@skaarthik , @slyons , @jaceklaskowski  
can you suggest me why the method sparkSession.Read().Jdbc(string url,string table, string columnName, string loweBound, string upperBound, int numPArtitions, Dictionary(string, string) connectionProperties) is now working for me i already generated an issue regarding it.

**Comment by jaceklaskowski** [comment]
I've never worked with Mobius and so the entire environment is completely new to me.

I can only comment on the NPE exception you face.

```
Caused by: java.lang.NullPointerException
at java.lang.ProcessBuilder.start(ProcessBuilder.java:1010)
at org.apache.hadoop.util.Shell.runCommand(Shell.java:482)
at org.apache.hadoop.util.Shell.run(Shell.java:455)
at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:715)
at org.apache.hadoop.fs.FileUtil.chmod(FileUtil.java:873)
at org.apache.hadoop.fs.FileUtil.chmod(FileUtil.java:853)
at org.apache.spark.util.Utils$.fetchFile(Utils.scala:471)
at org.apache.spark.executor.Executor$$anonfun$org$apache$spark$executor$Executor$$updateDependencies$5.apply(Executor.scala:488)
at org.apache.spark.executor.Executor$$anonfun$org$apache$spark$executor$Executor$$updateDependencies$5.apply(Executor.scala:480)
```

That happens when an executor tries to download the dependencies of a task and _somehow_ does not get what's necessary. You should look for **Fetching** in the logs (of executors) to find what files or jars cause this.

The messages should be as follows:

```
Fetching [name] with timestamp [timestamp]
```
