### ISSUE TITLE
Error when using SparkContext.TextFile to read file via wasb 

### ISSUE THREAD

**Issue by WilliamBerryiii** [Microsoft/Mobius#678]
I'm attempting to run the word count example by reading a file from an HDInsights Cluster's attached blob storage.  I'm passing the file path in and appending the  core-site.xml `fs.defaultFS` node value to form the wasb url before passing that into TextFile.  

The resulting error: 
``` 
[2018-01-10T17:45:27.1063310Z] [wn0-x] [Error] [JvmBridge] JVM method execution failed: Constructor failed for class org.apache.spark.api.csharp.CSharpRDD when called with 9 parameters ([Index=1, Type=JvmObjectReference, Value=11], [Index=2, Type=Byte[], Value=System.Byte[]], [Index=3, Type=JvmObjectReference, Value=8], [Index=4, Type=JvmObjectReference, Value=9], [Index=5, Type=Boolean, Value=False], [Index=6, Type=String, Value=CSharpWorker.exe], [Index=7, Type=String, Value=1.0], [Index=8, Type=JvmObjectReference, Value=10], [Index=9, Type=null, Value=null], )
[2018-01-10T17:45:27.1064200Z] [wn0-x] [Error] [JvmBridge] java.lang.NoSuchMethodError: org.apache.spark.api.python.PythonFunction.<init>([BLjava/util/Map;Ljava/util/List;Ljava/lang/String;Ljava/lang/String;Ljava/util/List;Lorg/apache/spark/Accumulator;)V
	at org.apache.spark.sql.api.csharp.SQLUtils$.createCSharpFunction(SQLUtils.scala:55)
	at org.apache.spark.api.csharp.CSharpRDD.<init>(CSharpRDD.scala:40)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.spark.api.csharp.CSharpBackendHandler.handleMethodCall(CSharpBackendHandler.scala:167)
	at org.apache.spark.api.csharp.CSharpBackendHandler.handleBackendRequest(CSharpBackendHandler.scala:106)
	at org.apache.spark.api.csharp.CSharpBackendHandler.channelRead0(CSharpBackendHandler.scala:32)
	at org.apache.spark.api.csharp.CSharpBackendHandler.channelRead0(CSharpBackendHandler.scala:28)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:336)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:336)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:336)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:643)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:566)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:480)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:131)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:748)
```

the wasb file uri is formatted as such: 

`wasb://container@clustername.blob.core.windows.net/user/{username}/file.txt`

Is this possibly because Spark on HDInsights is not loading the azure storage jar, or is it an issue in Mobius?

**Comment by WilliamBerryiii** [comment]
Looks like this has nothing to do with wasb and everything to do with this error:
`JVM method execution failed: Constructor failed for class org.apache.spark.api.csharp.CSharpRDD`

**Comment by WilliamBerryiii** [comment]
Ah, looks to be related to: https://github.com/Microsoft/Mobius/issues/631

**Comment by WilliamBerryiii** [comment]
Was running an HDInsights Cluster with Spark 2.1.  After re-creating the cluster with Spark 2.0 everything started to work.
