### ISSUE TITLE
failed to run SparkClrKafka

### ISSUE THREAD

**Issue by unruledboy** [Microsoft/Mobius#682]
Hi,

My environment:
- spark-2.0.2-bin-hadoop2.7
- hadoop is NOT installed

I **modified** the word count example not using the checkpoint due to it kept through error as: java.lang.IllegalArgumentException: requirement failed: Spark Streaming cannot be initialized with both SparkContext and checkpoint as null

And run the batch word count example like this:

C:\Mobius-master\build\runtime\scripts\sparkclr-submit.cmd --verbose --jars C:\Mobius-master\build\runtime\dependencies\spark-csv_2.10-1.4.0.jar,C:\Mobius-master\build\runtime\dependencies\commons-csV-1.4.jar --exe SparkClrKafka.exe C:\Mobius-master\examples\Streaming\Kafka\bin\Debug\ localhost:9092 test C:\Hadoop\CheckPoint C:\Output\WordCount

Parameters:
1. localhost:9092
2. test
3. C:\Hadoop\CheckPoint
4. C:\DataLake\Output\WordCount
 
And I get the output like the following. I read about the issue at https://github.com/Microsoft/Mobius/issues/631 and follow the instruction but still same.

Any idea? Thanks.

Using properties file: null
Parsed arguments:
  master                  local[*]
  deployMode              null
  executorMemory          null
  executorCores           null
  totalExecutorCores      null
  propertiesFile          null
  driverMemory            null
  driverCores             null
  driverExtraClassPath    null
  driverExtraLibraryPath  null
  driverExtraJavaOptions  null
  supervise               false
  queue                   null
  numExecutors            null
  files                   null
  pyFiles                 null
  archives                null
  mainClass               org.apache.spark.deploy.csharp.CSharpRunner
  primaryResource         file:/C:/Mobius-master/build/runtime/lib/spark-clr_2.11-2.0.200.jar
  name                    SparkClrKafka
  childArgs               [C:\Mobius-master\examples\Streaming\Kafka\bin\Debug\ C:\Mobius-master\examples\Streaming\Kafka\bin\Debug\SparkClrKafka.exe localhost:9092 test C:\Hadoop\CheckPoint C:\Output\WordCount]
  jars                    file:/C:/Mobius-master/build/runtime/dependencies/spark-csv_2.10-1.4.0.jar,file:/C:/Mobius-master/build/runtime/dependencies/commons-csV-1.4.jar
  packages                null
  packagesExclusions      null
  repositories            null
  verbose                 true

Spark properties used, including those specified through
 --conf and those from the properties file null:

Main class:
org.apache.spark.deploy.csharp.CSharpRunner
Arguments:
C:\Mobius-master\examples\Streaming\Kafka\bin\Debug\
C:\Mobius-master\examples\Streaming\Kafka\bin\Debug\SparkClrKafka.exe
localhost:9092
test
C:\Hadoop\CheckPoint
C:\Output\WordCount
System properties:
SPARK_SUBMIT -> true
spark.app.name -> SparkClrKafka
spark.jars -> file:/C:/Mobius-master/build/runtime/dependencies/spark-csv_2.10-1.4.0.jar,file:/C:/Mobius-master/build/runtime/dependencies/commons-csV-1.4.jar,file:/C:/Mobius-master/build/runtime/lib/spark-clr_2.11-2.0.200.jar
spark.submit.deployMode -> client
spark.master -> local[*]
Classpath elements:
file:/C:/Mobius-master/build/runtime/lib/spark-clr_2.11-2.0.200.jar
file:/C:/Mobius-master/build/runtime/dependencies/spark-csv_2.10-1.4.0.jar
file:/C:/Mobius-master/build/runtime/dependencies/commons-csV-1.4.jar

Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
18/02/22 14:21:58 INFO CSharpRunner: Starting CSharpBackend!
18/02/22 14:21:58 INFO CSharpRunner: Port number used by CSharpBackend is 53688
18/02/22 14:21:58 INFO CSharpRunner: Adding key=spark.jars and value=file:/C:/Mobius-master/build/runtime/dependencies/spark-csv_2.10-1.4.0.jar,file:/C:/Mobius-master/build/runtime/dependencies/commons-csV-1.4.jar,file:/C:/Mobius-master/build/runtime/lib/spark-clr_2.11-2.0.200.jar to environment
18/02/22 14:21:58 INFO CSharpRunner: Adding key=spark.app.name and value=SparkClrKafka to environment
18/02/22 14:21:58 INFO CSharpRunner: Adding key=spark.submit.deployMode and value=client to environment
18/02/22 14:21:58 INFO CSharpRunner: Adding key=spark.master and value=local[*] to environment
18/02/22 14:21:59 INFO SparkContext: Running Spark version 2.0.2
18/02/22 14:21:59 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
18/02/22 14:21:59 INFO SecurityManager: Changing view acls to: Administrator
18/02/22 14:21:59 INFO SecurityManager: Changing modify acls to: Administrator
18/02/22 14:21:59 INFO SecurityManager: Changing view acls groups to:
18/02/22 14:21:59 INFO SecurityManager: Changing modify acls groups to:
18/02/22 14:21:59 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(Administrator); groups with view permissions: Set(); users  with modify permissions: Set(Administrator); groups with modify permissions: Set()
18/02/22 14:21:59 INFO Utils: Successfully started service 'sparkDriver' on port 53698.
18/02/22 14:22:00 INFO SparkEnv: Registering MapOutputTracker
18/02/22 14:22:00 INFO SparkEnv: Registering BlockManagerMaster
18/02/22 14:22:00 INFO DiskBlockManager: Created local directory at C:\Users\Administrator\AppData\Local\Temp\2\blockmgr-2071a8bc-68d7-402d-afbf-c4caf69f286a
18/02/22 14:22:00 INFO MemoryStore: MemoryStore started with capacity 366.3 MB
18/02/22 14:22:00 INFO SparkEnv: Registering OutputCommitCoordinator
18/02/22 14:22:00 INFO Utils: Successfully started service 'SparkUI' on port 4040.
18/02/22 14:22:00 INFO SparkUI: Bound SparkUI to 0.0.0.0, and started at http://10.61.195.229:4040
18/02/22 14:22:00 INFO SparkContext: Added JAR file:/C:/Mobius-master/build/runtime/dependencies/spark-csv_2.10-1.4.0.jar at spark://10.61.195.229:53698/jars/spark-csv_2.10-1.4.0.jar with timestamp 1519269720470
18/02/22 14:22:00 INFO SparkContext: Added JAR file:/C:/Mobius-master/build/runtime/dependencies/commons-csV-1.4.jar at spark://10.61.195.229:53698/jars/commons-csV-1.4.jar with timestamp 1519269720470
18/02/22 14:22:00 INFO SparkContext: Added JAR file:/C:/Mobius-master/build/runtime/lib/spark-clr_2.11-2.0.200.jar at spark://10.61.195.229:53698/jars/spark-clr_2.11-2.0.200.jar with timestamp 1519269720470
18/02/22 14:22:00 INFO Executor: Starting executor ID driver on host localhost
18/02/22 14:22:00 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 53709.
18/02/22 14:22:00 INFO NettyBlockTransferService: Server created on 10.61.195.229:53709
18/02/22 14:22:00 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 10.61.195.229, 53709)
18/02/22 14:22:00 INFO BlockManagerMasterEndpoint: Registering block manager 10.61.195.229:53709 with 366.3 MB RAM, BlockManagerId(driver, 10.61.195.229, 53709)
18/02/22 14:22:00 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 10.61.195.229, 53709)
18/02/22 14:22:00 INFO CSharpBackendHandler: Connecting to a callback server at port 53711
18/02/22 14:22:01 INFO VerifiableProperties: Verifying properties
18/02/22 14:22:01 INFO VerifiableProperties: Property auto.offset.reset is overridden to smallest
18/02/22 14:22:01 INFO VerifiableProperties: Property group.id is overridden to
18/02/22 14:22:01 INFO VerifiableProperties: Property zookeeper.connect is overridden to
18/02/22 14:22:02 ERROR CSharpBackendHandler: Exception caught:
java.io.IOException: An existing connection was forcibly closed by the remote host
        at sun.nio.ch.SocketDispatcher.read0(Native Method)
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
        at sun.nio.ch.IOUtil.read(IOUtil.java:192)
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
        at io.netty.buffer.UnpooledUnsafeDirectByteBuf.setBytes(UnpooledUnsafeDirectByteBuf.java:447)
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:881)
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:242)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:119)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
        at java.lang.Thread.run(Thread.java:748)
18/02/22 14:22:02 INFO CSharpRunner: Closing CSharpBackend
18/02/22 14:22:02 INFO CSharpBackend: Requesting to close all call back sockets.
18/02/22 14:22:02 INFO CSharpRunner: Return CSharpBackend code -532462766
18/02/22 14:22:02 INFO Utils: Utils.exit() with status: -532462766, maxDelayMillis: 1000
18/02/22 14:22:02 INFO SparkContext: Invoking stop() from shutdown hook
18/02/22 14:22:02 INFO SparkUI: Stopped Spark web UI at http://10.61.195.229:4040
18/02/22 14:22:02 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
18/02/22 14:22:02 INFO MemoryStore: MemoryStore cleared
18/02/22 14:22:02 INFO BlockManager: BlockManager stopped
18/02/22 14:22:02 INFO BlockManagerMaster: BlockManagerMaster stopped
18/02/22 14:22:02 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
18/02/22 14:22:02 INFO SparkContext: Successfully stopped SparkContext
18/02/22 14:22:02 INFO ShutdownHookManager: Shutdown hook called
18/02/22 14:22:02 INFO ShutdownHookManager: Deleting directory C:\Users\Administrator\AppData\Local\Temp\2\spark-f12893a8-b831-4712-9891-d0bf3d4fea43

**Comment by unruledboy** [comment]
it is the SPARK_HOME issue, had to open command line after changed to proper version. the spark version has to be same as the one in \build\runtime\lib

**Comment by unruledboy** [comment]
And, if I use pipe redirect the std output to a file, I can see extra error like this:


Unhandled Exception: System.Runtime.Serialization.SerializationException: Type 'Microsoft.Spark.CSharp.Examples.SparkClrKafkaExample+<>c__DisplayClass0_0' in Assembly 'SparkClrKafka, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' is not marked as serializable.
   at System.Runtime.Serialization.FormatterServices.InternalGetSerializableMembers(RuntimeType type)
   at System.Runtime.Serialization.FormatterServices.<>c__DisplayClass9_0.<GetSerializableMembers>b__0(MemberHolder _)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at System.Runtime.Serialization.FormatterServices.GetSerializableMembers(Type type, StreamingContext context)
   at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitMemberInfo()
   at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitSerialize(Object obj, ISurrogateSelector surrogateSelector, StreamingContext context, SerObjectInfoInit serObjectInfoInit, IFormatterConverter converter, ObjectWriter objectWriter, SerializationBinder binder)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Write(WriteObjectInfo objectInfo, NameInfo memberNameInfo, NameInfo typeNameInfo)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Serialize(Object graph, Header[] inHeaders, __BinaryWriter serWriter, Boolean fCheck)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph, Header[] headers, Boolean fCheck)
   at Microsoft.Spark.CSharp.Streaming.DStream`1.ForeachRDD(Action`2 f)
   at Microsoft.Spark.CSharp.Streaming.DStream`1.ForeachRDD(Action`1 f)
   at Microsoft.Spark.CSharp.Examples.SparkClrKafkaExample.Main(String[] args) in C:\Users\wilson.chen\Downloads\Mobius-master\examples\Streaming\Kafka\Program.cs:line 53
