### ISSUE TITLE
error using sparkclr-submit debug mode

### ISSUE THREAD

**Issue by MrComic** [Microsoft/Mobius#690]
im using Spark v 2.3.0 with hadoop v 2.7 
when i enter spark sparkclr-submit debug it gives me this error:

[sparkclr-submit.cmd] SPARKCLR_HOME is set to F:\spark\spark-clr_2.11-2.0.200\runtime\scripts\..
[sparkclr-submit.cmd] SPARKCLR_JAR=spark-clr_2.11-2.0.200.jar
[sparkclr-submit.cmd] LAUNCH_CLASSPATH="F:\spark\spark-clr_2.11-2.0.200\runtime\scripts\..\lib\spark-clr_2.11-2.0.200.jar;F:\spark\spark-2.3.0-bin-hadoop2.7\jars\*"
Exception in thread "main" java.lang.AbstractMethodError: org.apache.spark.deploy.csharp.CSharpRunner$.initializeLogIfNecessary(ZZ)Z
        at org.apache.spark.internal.Logging$class.initializeLogIfNecessary(Logging.scala:99)
        at org.apache.spark.deploy.csharp.CSharpRunner$.initializeLogIfNecessary(CSharpRunner.scala:26)
        at org.apache.spark.internal.Logging$class.log(Logging.scala:46)
        at org.apache.spark.deploy.csharp.CSharpRunner$.log(CSharpRunner.scala:26)
        at org.apache.spark.internal.Logging$class.logInfo(Logging.scala:54)
        at org.apache.spark.deploy.csharp.CSharpRunner$.logInfo(CSharpRunner.scala:26)
        at org.apache.spark.deploy.csharp.CSharpRunner$.main(CSharpRunner.scala:77)
        at org.apache.spark.deploy.csharp.CSharpRunner.main(CSharpRunner.scala)

**Comment by purefunkce** [comment]
Try using Spark 2.0.2 instead of 2.3.0

**Comment by MrComic** [comment]
thanks it helped me a lot
