### ISSUE TITLE
Switch to fluent assertion

### ISSUE THREAD

**Issue by danielli90** [Microsoft/Mobius#75]
Currently `Assert()` in Microsoft.VisualStudio.QualityTools.UnitTestFramework are used in samples and unit tests code. [FluentAssertions](http://www.fluentassertions.com/) (or [N-Fluent](http://n-fluent.net/)) offers a fluent style assertion, helps pinpoint the cause of assertion much more efficient. See original comment by @jthelin suggested in #68. Create this issue as suggestions to adopt fluent assertion as we write/update assertion in samples and unit test code.

**Comment by kai-zeng** [comment]
@rapoth and I are looking into SparkCLR compatibility in Linux (#105). 
We find that the xbuild tool on Mono cannot build SparkCLR due to failure to restore MSTest. I have experimented with changing SparkCLR unit tests to use the NUnit test framework, where xbuild is able to restore and build the project smoothly.

So I suggest we consider switching to NUnit for unit test, as NUnit:
* is available on NuGet
* is comparable to MSTest in functionality
* has visual studio plugins, 
* works with FluentAssertions

Any thoughts on this? If we are fine with this, I can go ahead and push a PR.

**Comment by danielli90** [comment]
Sounds reasonable to me. Per this article - http://www.florian-rappl.de/News/Page/275/convert-mstest-to-nunit, it seems the cost is manageable – it mentioned http://www.monodevelop.com/, we may want to check out.

Thx
Daniel

**Comment by skaarthik** [comment]
Switching to NUnit sounds good to me. Please send PR.

**Comment by hebinhuang** [comment]
All, I would like to close this issue, because @kai-zeng already checked in the NUnit and used NUnit.Assert in our tests.

Here are the comparison of exception output for NFluent, FluentAssertions, and NUnit.Assert. NUnit.Assert is enough in our test. I will close the issue by tomorrow afternoon, please let me know if you have any concerns or suggestions before tomorrow afternoon.

NFluent.FluentCheckException:
The checked value is different from the expected one.
The checked value:
        [20]
The expected value:
        [700]
   at NFluent.Helpers.EqualityHelper.IsEqualTo(Object instance, Object expected)
   at NFluent.ObjectCheckExtensions.<>c__DisplayClass1`1.<IsEqualTo>b__0()
   at NFluent.Extensibility.Checker`2.ExecuteCheck(Action action, String negatedExceptionMessage)
   at NFluent.ObjectCheckExtensions.IsEqualTo[T](ICheck`1 check, Object expected)
   at NFluent.ObjectCheckExtensions.IsEqualTo[T](ICheck`1 check, T expected)
   at ConsoleApplication2.Program.Main(String[] args) in D:\MyWorks\ConsoleApplication2\ConsoleApplication2\Program.cs:line 19

NUnit.Framework.AssertionException:   Expected: 700
  But was:  20

   at NUnit.Framework.Assert.That[TActual](TActual actual, IResolveConstraint expression, String message, Object[] args)
   at NUnit.Framework.Assert.AreEqual(Object expected, Object actual)
   at ConsoleApplication2.Program.Main(String[] args) in D:\MyWorks\ConsoleApplication2\ConsoleApplication2\Program.cs:line 29

FluentAssert.Exceptions.ShouldBeEqualAssertionException:   Expected: 700
  But was:  20

   at FluentAssert.AssertExtensions.ShouldBeEqualTo[T](T item, T expected, Func`1 getErrorMessage) in c:\projects\FluentAssert\src\FluentAssert\AssertExtensions.cs:line 116
   at FluentAssert.AssertExtensions.ShouldBeEqualTo[T](T item, T expected) in c:\projects\FluentAssert\src\FluentAssert\AssertExtensions.cs:line 60
   at ConsoleApplication2.Program.Main(String[] args) in D:\MyWorks\ConsoleApplication2\ConsoleApplication2\Program.cs:line 39
